FROM randomdude/gcc-cross-x86_64-elf

RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y nasm
RUN apt-get install -y qemu-system-x86
RUN apt-get install -y binutils
RUN apt-get install -y gcc
RUN apt-get install -y ovmf
RUN apt-get install -y make
RUN apt-get install -y wget

VOLUME /root/env
WORKDIR /root/env